### Importing necessary libraries  which we gonna be working with

In [1]:
import pandas as pd
import sqlite3

### Lets pull csv file to df variable as pandas dataframe

In [2]:
df=pd.read_csv("orders.csv")
df.head(2) # Lets see our dataframe

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011

### Connecting sqlite to our dataframe

In [3]:
conn = sqlite3.connect("sales.db") 
df.to_sql("orders", conn, if_exists="replace", index=False)

print("Loaded into SQLite")

Loaded into SQLite

### Lets calculate revenue by category vie sql
##### I want to see  which category is making the most revenu. To do so, basic calculations will be done via sql's SUM(), GROUP BY and ORDER BY queries

In [4]:
query = """
SELECT Category, SUM(Sales) AS revenue
FROM orders
GROUP BY Category
ORDER BY revenue DESC
"""
# Creating a new variable result, to save our filtered data
result = pd.read_sql(query, conn)
result

          category    revenue
0  Office Supplies  2791051.0
1       Technology  2639942.0
2        Furniture  2407930.0

### Now We will save our calculated revenue to a new csv file, so that our defined kpi's will be kept separately in a new file

In [5]:
result.to_csv("revenue_by_category.csv", index=False)

### Down below I have  calculated revenue by product name, so that we will be able to see which products are generating the most revenue

In [6]:
top_products = pd.read_sql("""
SELECT Product_Name, SUM(Sales) AS revenue
FROM orders
GROUP BY Product_Name
ORDER BY revenue DESC
LIMIT 10
""", conn)

top_products

                                        product_name  revenue
0                      Eldon File Cart, Single Width  31322.0
1                     Rogers File Cart, Single Width  22650.0
2                      Tenex File Cart, Single Width  20779.0
3                      Smead File Cart, Single Width  20779.0
4  Office Star Executive Leather Armchair, Adjust...  19379.0
5                       Fellowes Lockers, Industrial  19175.0
6                          Smead Lockers, Industrial  18656.0
7                        Hewlett Copy Machine, Color  16859.0
8                               Rogers Lockers, Blue  16503.0
9                       Fellowes Lockers, Wire Frame  16470.0